@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title "Digital Wallet Full Cycle"

Person(client, "Client", "Digital Wallet User")
System_Ext(payment_gateway, "Payment Gateway", "Payment Processor")

System_Boundary(digital_wallet, "Digital Wallet") {
  Container(spa, "SPA", "React", "Digital Wallet Web App")
  Container(wallet_core, "Wallet Core", "TS", "Wallet Core is responsible for the transactions")
  Container(balance_service, "Balance Microsservice", "TS", "Returns customer balance")
  Container(statement_service, "Statement Microsservice", "TS", "Returns customer statements")
  Container(payment_acl, "Payment ACL", "TS", "Anticorruption Layer for Payment Gateway")
}

@enduml